# Generated by Django 2.0.7 on 2018-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
