# Generated by Django 2.0.7 on 2018-07-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180723_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
