# Generated by Django 2.0.7 on 2018-07-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_slug'),
        ('blog', '0002_auto_20180722_1727'),
    ]

    operations = [
    ]
